# fly.toml app configuration file generated for prod-od-api on 2023-06-15T10:39:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "prod-od-api"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    restart_limit = 0
