name: deploy
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-to-fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.3"

      - name: Build Swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest && swag init

      - uses: superfly/flyctl-actions/setup-flyctl@master

      # Prod Deploy
      - if: github.ref == 'refs/heads/main'
        run: flyctl deploy --remote-only -c ./fly/prod-fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.PROD_FLY_API_TOKEN }}

      # Dev Deploy
      - if: github.ref == 'refs/heads/dev'
        run: flyctl deploy --remote-only -c ./fly/dev-fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.DEV_FLY_API_TOKEN }}
